/// Les 58 wilayas d'Algérie (découpage 2019), **pour le sélecteur de zone
/// uniquement**.
///
/// ⚠️ **Ce n'est PAS une liste de validation.** Le serveur accepte n'importe
/// quelle chaîne comme wilaya (`SaveServiceZoneDto` ne borne que la longueur,
/// pas les valeurs — même parti pris que `transporteur.dto.ts`, pour ne pas
/// refuser une wilaya renommée ou créée). Cette liste sert seulement à proposer
/// des choix cohérents dans l'éditeur de zone de l'entreprise ; une zone déjà
/// enregistrée avec un autre libellé reste affichée et modifiable.
///
/// L'ordre est celui des numéros de wilaya, le plus familier en Algérie.
const List<String> algerianWilayas = [
  'Adrar',
  'Chlef',
  'Laghouat',
  'Oum El Bouaghi',
  'Batna',
  'Béjaïa',
  'Biskra',
  'Béchar',
  'Blida',
  'Bouira',
  'Tamanrasset',
  'Tébessa',
  'Tlemcen',
  'Tiaret',
  'Tizi Ouzou',
  'Alger',
  'Djelfa',
  'Jijel',
  'Sétif',
  'Saïda',
  'Skikda',
  'Sidi Bel Abbès',
  'Annaba',
  'Guelma',
  'Constantine',
  'Médéa',
  'Mostaganem',
  "M'Sila",
  'Mascara',
  'Ouargla',
  'Oran',
  'El Bayadh',
  'Illizi',
  'Bordj Bou Arréridj',
  'Boumerdès',
  'El Tarf',
  'Tindouf',
  'Tissemsilt',
  'El Oued',
  'Khenchela',
  'Souk Ahras',
  'Tipaza',
  'Mila',
  'Aïn Defla',
  'Naâma',
  'Aïn Témouchent',
  'Ghardaïa',
  'Relizane',
  'Timimoun',
  'Bordj Badji Mokhtar',
  'Ouled Djellal',
  'Béni Abbès',
  'In Salah',
  'In Guezzam',
  'Touggourt',
  'Djanet',
  "El M'Ghair",
  'El Meniaa',
];
